### ISSUE TITLE
ros2 Iron: rqt_bag displays wrong type in raw view

### ISSUE THREAD

**Issue by tcm0116** [ros-visualization/rqt_bag#147] opened 2024-01-19 15:59 UTC
When displaying the raw view for multiple topics in a bag file, rqt_bag always uses the same message type for all raw views:

![Screenshot from 2024-01-19 10-48-42](https://github.com/ros-visualization/rqt_bag/assets/1868773/55e24d16-0cbd-43f8-91c7-d58e496223d4)

This can be recreated by:

Terminal 1:
1. `source /opt/ros/iron/setup.bash`
2. `ros2 run turtlesim turtlesim_node`

Terminal 2:
1. `source /opt/ros/iron/setup.bash`
2. `ros2 bag record -a -o rosbag`
3. After several seconds, press `Ctrl+C` to stop the recording
4. `rqt_bag rosbag`
5. Right-click on `/turtle1/color_sensor` and select View and then select Raw
6. Right-click on `/turtle1/pose` and select View and then select Raw
7. Select the Next frame button in the main toolbar until data is displayed in the raw views
8. The message type and data layout in both raw views will be `turtlesim/msg/Pose`
9. Select the Next frame button in the `/turtle1/color_sensor__Raw` view
10. The message type and data layout in both raw views will be `turtlesim/msg/Color`
11. Select the Next frame button in the `/turtle1/pose__Raw` view
12. The message type and data layout in both raw views will be `turtlesim/msg/Pose`

**Comment by arneboe** [comment] 2024-02-14 09:53
I am having the same issue in ros2 iron.
Any updates on this?

**Comment by Yadunund** [comment] 2024-02-14 10:01
I'lll close this ticket since it's a duplicate of https://github.com/ros-visualization/rqt_bag/issues/136

**Closed as completed by Yadunund** 2024-02-14 10:01 UTC
