### ISSUE TITLE
Crash on Kinetics. ImportError

### ISSUE THREAD

**Issue by facontidavide** [ros-visualization/rqt_bag#19] opened 2017-11-03 09:45 UTC
I am experiencing a problem roughly similar to this:

https://github.com/ros-visualization/rqt/issues/112

> Traceback (most recent call last):
>   File "/opt/ros/kinetic/lib/rqt_bag/rqt_bag", line 5, in <module>
>     from rqt_bag.bag import Bag
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag.py", line 39, in <module>
>     from .bag_widget import BagWidget
>   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_bag/bag_widget.py", line 40, in <module>
>     from python_qt_binding.QtCore import Qt, qInfo, qWarning, Signal
> ImportError: cannot import name qInfo

Unfortunately I followed those suggestion but my problem seems to be different.

these are some information from my system.

rosversion rqt_bag: 0.4.10
```
python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import python_qt_binding
>>> print(python_qt_binding.QT_BINDING)
pyqt
>>> from python_qt_binding.QtWidgets import QWidget
>>> print(python_qt_binding.QT_BINDING_VERSION)
5.5.1
>>> print(python_qt_binding.QT_BINDING_MODULES)
{'QtGui': <module 'PyQt5.QtGui' from '/usr/lib/python2.7/dist-packages/PyQt5/QtGui.x86_64-linux-gnu.so'>, 'QtSvg': <module 'PyQt5.QtSvg' from '/usr/lib/python2.7/dist-packages/PyQt5/QtSvg.x86_64-linux-gnu.so'>, 'QtWidgets': <module 'PyQt5.QtWidgets' from '/usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so'>, 'QtNetwork': <module 'PyQt5.QtNetwork' from '/usr/lib/python2.7/dist-packages/PyQt5/QtNetwork.x86_64-linux-gnu.so'>, 'QtXml': <module 'PyQt5.QtXml' from '/usr/lib/python2.7/dist-packages/PyQt5/QtXml.x86_64-linux-gnu.so'>, 'QtWebKitWidgets': <module 'PyQt5.QtWebKitWidgets' from '/usr/lib/python2.7/dist-packages/PyQt5/QtWebKitWidgets.x86_64-linux-gnu.so'>, 'QtCore': <module 'PyQt5.QtCore' from '/usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so'>, 'QtOpenGL': <module 'PyQt5.QtOpenGL' from '/usr/lib/python2.7/dist-packages/PyQt5/QtOpenGL.x86_64-linux-gnu.so'>}
>>> import PyQt5
>>> from PyQt5 import QtWidget
>>> print PyQt5.QtCore.PYQT_VERSION_STR
5.5.1

```

**Comment by dirk-thomas** [comment] 2017-11-03 14:58
Duplicate of #15.

**Closed by dirk-thomas** 2017-11-03 14:58 UTC
