### ISSUE TITLE
ValueError: bottom cannot be >= top

### ISSUE THREAD

**Issue by WesleyYue** [ros-visualization/rqt_bag#18] opened 2017-11-02 16:21 UTC
Reproducable rqt_bag crash

1. `rqt_bag any_rosbag.bag`
2. Plot a topic
3. Drag the plotting sub-window from the right to above the timeline
4. rqt_bag will crash

```
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rqt_plot/data_plot/mat_data_plot.py", line 107, in resizeEvent
    self.figure.tight_layout()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1755, in tight_layout
    self.subplots_adjust(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1620, in subplots_adjust
    self.subplotpars.update(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 232, in update
    raise ValueError('bottom cannot be >= top')
```

**Comment by dirk-thomas** [comment] 2017-12-13 10:53
This looks like a duplicate of ros-visualization/rqt#110. Therefore I will close this ticket.

**Closed by dirk-thomas** 2017-12-13 10:53 UTC
Labels: duplicate
